### ISSUE TITLE
Action Failed: Branches do not exist

### ISSUE THREAD

**Issue by kemra102** [updatecli/updatecli#1905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have a GitLab CI job that runs to update the Helm deps of our Helm based API deployments. Each API is a GitLab repo with a branch per environment (prefixed **env/**, e.g. **env/test**). The CI job iterates for each branch calling `updatecli` for each branch (each iteration has it's own config file due to the different branch names).

On a random branch in the iteration we get an error like this one:

```sh
ACTIONS
========
Pipeline "Bump dependency \"simple-api\" for Helm chart \"example-app\"" failed
Skipping due to:
	action stage:	"remote branches \"updatecli_02dd09819960503297b29201e46ffd28df93fe95b2e1cea5c31810cdcc87445b\" and \"env/test\" do not exist, we can't open a mergerequest"
```

However both branches mentioned in the error DO exist. The error causes the pipeline to correctly fail.

### Expected Behavior

MRs are created for each **env/** branch.

### Environment

```markdown
- OS: RHEL8
- updatecli: v0.71.0
```

### Anything else?

[example-updatecli-config.txt](https://github.com/updatecli/updatecli/files/14110994/example-updatecli-config.txt)

**Comment by olblak** [comment]
Hi @kemra102,
Is it still something you are experiencing?
We made quite a lot of improvement since Updatecli version v0.71.0
We are about to release v0.114.0

**Comment by kemra102** [comment]
@olblak I think the team I implemented this for has since moved onto to other solutions (for reasons besides this error - I think they used `updatecli` for some time).

Given my current circumstances I don't have easy access to the original code so it may be worth assuming this is either fixed unless someone else reports otherwise.

**Comment by chrxmvtik** [comment]
@olblak can we reopen this issue? This error still persist for us.

Updatecli version: v0.118.0
Gitlab selfhosted version: v18.6.0

It happens randomly, for example:

First job in the pipeline works fine, it creates changes and publish MR to repo X, second job is triggered right after first one finish - it is also supposed to create changes and publish MR to repo X, but it fails, and says that branch <updatecli_temporary_branch> and "main" does not exist.

When I set a job to retry few times, it finally succeeds, but it shouldn't work this way.

When I downgraded to version v0.100.0, it works fine.

**Comment by olblak** [comment]
> When I downgraded to version v0.100.0, it works fine.
That's a good hint
